Backend updates for user model, routes and testing. event history rendered to dashboard for visibility.
Seyi-Toluhi/The-Neurons pull request #17
Opened 2024-04-29 14:30 UTC by Seyi-Toluhi

Backend updates for user model, routes and testing. event history rendered to dashboard for visibility. Tests for signup and login component updated

2024-04-30 10:19 UTC, tomgame984 requested changes

2024-04-30 10:19 UTC, tomgame984 commented on Frontend/tests/pages/SignupPage.test.jsx
> +    test("throw an error on unsuccessful signup`", async () => {
Replicate failed signup test to include:

- All details except first name
- All details except last name
- All details except email
- All details except neurodiversity

2024-04-30 10:19 UTC, tomgame984 commented on api/models/mongoose.seed.js
To be refactored

2024-04-30 10:19 UTC, tomgame984 commented on api/tests/models/user.test.js
>    it("has a bio", () => {
```suggestion
  it("has a neurodiversity", () => {
```

2024-05-01 09:30 UTC, tomgame984 submitted a review, later dismissed

2024-05-01 09:31 UTC, JackCollett submitted a review, later dismissed

2024-05-01 09:35 UTC, JackCollett approved these changes

2024-05-01 09:35 UTC, tomgame984 approved these changes

2024-05-01 09:36 UTC, merged