Skeleton version of backend structure. We will be building on top of this.
Seyi-Toluhi/The-Neurons pull request #6
Opened 2024-04-24 12:35 UTC by F-Gulmez

2024-04-24 12:58 UTC, Seyi-Toluhi commented on api/.gitignore
can we get the .DS_Store inside the gitignore.

2024-04-24 13:25 UTC, tomgame984 requested changes
Test cases reviewed and OK as baseline tests.  Further tests likely to be required as app develops.  
Please make amendments as per comments and advise when done.

2024-04-24 13:25 UTC, tomgame984 commented on api/tests/lib/token.test.js
> +    test("returns a token containing user_id that is valid for 10 minutes", () => {
Test wording to be amend to 30 minutes

2024-04-24 13:25 UTC, tomgame984 commented on api/tests/lib/token.test.js
> +      // Token is valid for 600 seconds (30 minutes)
Change "Token is valid for 1800 seconds".

2024-04-24 14:42 UTC, F-Gulmez reviewed
Made the changes asked and committed in the branch

2024-04-24 14:43 UTC, F-Gulmez reviewed
Implemented requested changes

2024-04-24 14:53 UTC, F-Gulmez reviewed
Done

2024-04-25 09:36 UTC, tomgame984 submitted a review, later dismissed

2024-04-25 09:37 UTC, tomgame984 approved these changes

2024-04-25 09:38 UTC, Seyi-Toluhi approved these changes

2024-04-25 09:41 UTC, JackCollett approved these changes

2024-04-25 09:41 UTC, merged