signup page component created with UI tests passing
Seyi-Toluhi/The-Neurons pull request #8
Opened 2024-04-25 10:27 UTC by Seyi-Toluhi

We have written two tests for signup form UI to check that the input fields render and that when filled, the inputs become its values. We will include more tests for the actual form submission once the backend routes are set up.

2024-04-25 12:48 UTC, F-Gulmez submitted a review, later dismissed

2024-04-25 13:18 UTC, yulingyou requested changes

2024-04-25 13:18 UTC, yulingyou commented on Frontend/src/pages/SignupPage.jsx
> +    <h2>Signup</h2>
For better user experience and search engine optimisation, it is suggested to have a title tag on the signup page.

2024-04-25 13:23 UTC, Seyi-Toluhi commented on Frontend/src/pages/SignupPage.jsx
> +    <h2>Signup</h2>
ok i can get that sorted

2024-04-25 13:25 UTC, yulingyou commented on Frontend/src/pages/SignupPage.jsx
> +    <h2>Signup</h2>
Thank you!

2024-04-25 13:30 UTC, Seyi-Toluhi commented on Frontend/src/pages/SignupPage.jsx
> +    <h2>Signup</h2>
Done and i'll do same for login component

2024-04-25 13:44 UTC, yulingyou commented on Frontend/src/pages/SignupPage.jsx
> +    <h2>Signup</h2>
Hi Seyi, thanks! I just remembered that the title tag is supposed to be wrapped inside the `<head>` element. I'll double-check with the coach to see what their opinion is and let you know!

2024-04-25 14:22 UTC, Seyi-Toluhi commented on Frontend/src/pages/SignupPage.jsx
> +    <h2>Signup</h2>
yes Daisy, thats true for vanilla js. I am not sure how that works with React component as we've never had HTML headers in them. Would be good to know how to add headers to react components if possible.

2024-04-25 14:35 UTC, Seyi-Toluhi commented on Frontend/src/pages/SignupPage.jsx
> +    <h2>Signup</h2>
thats updated now daisy for this PR and login PR

2024-04-25 14:35 UTC, yulingyou commented on Frontend/src/pages/SignupPage.jsx
> +    <h2>Signup</h2>
The headers are currently in `Frontend/index.html`. Maybe for now, it's okay to hardcode the title. I've also added the suggestion to have a 'dynamic title' for our mirror board - proposed Features.

2024-04-25 14:58 UTC, yulingyou approved these changes

2024-04-26 09:30 UTC, JackCollett approved these changes

2024-04-26 09:35 UTC, merged